baseURL = 'https://afmohame.com/'
languageCode = 'en-us'
title = 'Mon savoir'
theme = 'gokarna'
[params]
    customcss = ["css/custom.css"]
    accentColor = "#967bb6 "
    avatarURL = "/logo.png"
    avatarSize = "size-xs"
    avatarAltText = "site logo"




[menu]
    [[menu.main]]
    name = "About"
    url = "about"
    weigth = 1

    [[menu.main]]
    name = "Arduino"
    url = "/arduino_uno_r3/"
    weigth = 1

    [[menu.main]]
    name = "Mijn projecten"
    url = "/project_pages/"
    weigth = 1

    [[menu.main]]
    name = "TESTING"
    url = "/test/"
    weigth = 1