baseURL = 'https://afmohame.com/'
languageCode = 'en-us'
title = '' 
theme = 'gokarna'
[params]
    customHeadHTML = '<link rel="stylesheet" href="/css/custom.css">'
    customCSS = ["css/custom.css"]
    accentColor = "#967bb6"
    avatarURL = "/LOGO.png"
    avatarSize = "size-s"
    avatarAltText = "site logo"
    socialIcons = [
        {name = "GitHub", url = "https://github.com/afmohame/"}
    ]


[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[menu]
    [[menu.main]]
    identifier = "GitHub"
    url = "https://github.com/afmohame/"
    weight = 100
    pre = "<span data-feather='github'></span>"
    [menu.main.params]
        newPage = true

    [[menu.main]]
    name = "Home"
    url = "#"
    weight = 1

    [[menu.main]]
    name = "About"
    url = "about"
    weight = 98


    [[menu.main]]
    name = "Reports"
    url = "/"
    identifier = "reports"
    weight = 2
    
    [[menu.main]]
    name = "Arduino Uno R3"
    url = "/arduino_uno_r3/"
    parent = "reports"
    weight = 2

    [[menu.main]]
    name = "More "
    url = "/report_page/"
    parent = "reports"
    weight = 3




    [[menu.main]]
    name = "Projects"
    url = "/project_pages/"
    identifier = "projects"
    weight = 3

    [[menu.main]]
    name = "MPU-6050 Accelerometer"
    url = "/MPU6050_accel/"
    parent = "projects"
    weight = 2

    [[menu.main]]
    name = "More"
    url = "/project_pages/"
    parent = "projects"
    weight = 3


    [[menu.main]]
    name = "TESTIdNG"
    url = "/test/"
    weight = 99
    
    